# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_day', models.IntegerField()),
                ('expense_day', models.IntegerField()),
                ('date_day', models.DateField()),
                ('cash_day', models.IntegerField()),
                ('card_day', models.IntegerField()),
                ('counter_day', models.IntegerField()),
                ('revenue', models.IntegerField()),
            ],
        ),
    ]
