# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureinn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expense', models.DateField()),
                ('maintainence_expense', models.IntegerField()),
                ('bills_expense', models.IntegerField()),
                ('inventory_expense', models.IntegerField()),
                ('diesel_expense', models.IntegerField()),
                ('salary_expense', models.IntegerField()),
                ('bulk_expense', models.IntegerField()),
                ('maintainence_text_expense', models.CharField(max_length=50)),
                ('bills_text_expense', models.CharField(max_length=50)),
                ('inventory_text_expense', models.CharField(max_length=50)),
                ('salary_text_expense', models.CharField(max_length=50)),
                ('bulk_text_expense', models.CharField(max_length=50)),
            ],
        ),
    ]
