# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureinn', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='total_expense',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
