# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatureinn', '0005_auto_20160229_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='date_day',
        ),
    ]
