# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatureinn', '0006_remove_day_date_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='title_day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
