# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_item',
            name='task_actual',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
