# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-24 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20160305_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_item',
            name='task_note',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
